import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ömer Faruk Çiçek
 */
public class Menu extends javax.swing.JFrame {
    
    DefaultTableModel model, model2, model3, model4;
    Veri veriIslemleri = new Veri();
    String kitap_adi_GE, kitap_yazari_GE, yayin_evi_GE, kitap_turu_GE, kitap_durumu_GE;
    String uye_adi_GE,cinsiyet_GE,dogum_tarihi_GE,telefon_GE,e_mail_GE;
    int kitapid, uyeid;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        model =(DefaultTableModel) jTable1.getModel();
        model2 =(DefaultTableModel) jTable2.getModel();
        model3 =(DefaultTableModel) jTable3.getModel();
        model4 =(DefaultTableModel) jTable4.getModel();
        uyeGoruntule();
        kitapGoruntule();
        uyeGoruntuleOdunc();
        kitapGoruntuleOdunc();
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        Feedback3.setText("Önce Aşağıdan Alıcıyı Daha Sonra İse Yukarıdan Kitabı Seçiniz");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        arama_cubugu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Fld_kitap_adi = new javax.swing.JTextField();
        Fld_yazar_adi = new javax.swing.JTextField();
        Fld_yayin_evi = new javax.swing.JTextField();
        Feedback = new javax.swing.JLabel();
        Kitap_Ekle = new javax.swing.JButton();
        Box_Kitap_Turu = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        guncelle = new javax.swing.JButton();
        sil = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        arama_cubugu1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Fld_Uye_adi = new javax.swing.JTextField();
        Fld_Telefon = new javax.swing.JTextField();
        Fld_dogum_tarihi = new javax.swing.JTextField();
        Feedback1 = new javax.swing.JLabel();
        Uye_Ekle = new javax.swing.JButton();
        Box_Cinsiyet = new javax.swing.JComboBox<>();
        guncelle1 = new javax.swing.JButton();
        sil1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Fld_Email = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Feedback3 = new javax.swing.JLabel();
        kitapVer = new javax.swing.JButton();
        kitapAl = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kütüphane Otomasyonu");
        setBackground(new java.awt.Color(0, 0, 153));
        setBounds(new java.awt.Rectangle(350, 100, 0, 0));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 255, 255));
        jButton1.setText("Kitap İşlemleri");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 0));
        jButton2.setText("Üye İşlemleri");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(525, 500));

        arama_cubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                arama_cubuguKeyReleased(evt);
            }
        });

        jLabel1.setText("Kitap Adı:");

        jLabel2.setText("Yazar Adı:");

        jLabel3.setText("Yayın Evi:");

        jLabel4.setText("Kitap Türü:");

        Feedback.setForeground(new java.awt.Color(255, 0, 0));

        Kitap_Ekle.setText("Yeni Kitap Ekle");
        Kitap_Ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kitap_EkleActionPerformed(evt);
            }
        });

        Box_Kitap_Turu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Araştırma", "Bilim", "Biyografi", "Edebiyat", "Eğitim", "Felsefe", "Hikaye", "İnceleme", "İş Ekonomi - Hukuk", "Kişisel Gelişim", "Masal", "Öykü", "Psikoloji", "Roman", "Sağlık", "Sanat - Tasarım - Müzik", "Şiir", "Tarih", "Yemek Kitapları" }));
        Box_Kitap_Turu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_Kitap_TuruActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Kitap Adı", "Yazar Adı", "Yayın Evi", "Kitap Türü", "Kitap Durumu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        guncelle.setText("Kitap Güncelle");
        guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleActionPerformed(evt);
            }
        });

        sil.setText("Kitap Sil");
        sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Geri");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setText("Kitap Ödünç Ver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Box_Kitap_Turu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(arama_cubugu)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Fld_kitap_adi, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(Fld_yazar_adi)
                            .addComponent(Fld_yayin_evi))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(guncelle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Kitap_Ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(arama_cubugu, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fld_kitap_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Kitap_Ekle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fld_yazar_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guncelle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fld_yayin_evi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_Kitap_Turu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(525, 500));

        arama_cubugu1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                arama_cubugu1KeyReleased(evt);
            }
        });

        jLabel5.setText("Üye Adı:");

        jLabel6.setText("Cinsiyet:");

        jLabel7.setText("Doğum Tarihi:");

        jLabel8.setText("Telefon:");

        Fld_dogum_tarihi.setToolTipText("Örn. 15.07.1991");
        Fld_dogum_tarihi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fld_dogum_tarihiActionPerformed(evt);
            }
        });

        Feedback1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Feedback1.setForeground(new java.awt.Color(255, 0, 0));

        Uye_Ekle.setText("Yeni Üye Ekle");
        Uye_Ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Uye_EkleActionPerformed(evt);
            }
        });

        Box_Cinsiyet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Erkek", "Kadın" }));
        Box_Cinsiyet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_CinsiyetActionPerformed(evt);
            }
        });

        guncelle1.setText("Üye Güncelle");
        guncelle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelle1ActionPerformed(evt);
            }
        });

        sil1.setText("Üye Sil");
        sil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sil1ActionPerformed(evt);
            }
        });

        jLabel9.setText("E-mail");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Üye Adı", "Cinsiyet", "Doğum Tarihi", "Telefon", "E-mail", "Kitapları"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("Geri");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Fld_dogum_tarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Fld_Uye_adi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Box_Cinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Fld_Telefon, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Fld_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Uye_Ekle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sil1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(guncelle1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(arama_cubugu1)))
                    .addComponent(Feedback1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(arama_cubugu1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Fld_Uye_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Uye_Ekle))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Box_Cinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fld_dogum_tarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(guncelle1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fld_Telefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sil1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fld_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(Feedback1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setPreferredSize(new java.awt.Dimension(525, 500));

        Feedback3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Feedback3.setForeground(new java.awt.Color(255, 0, 0));

        kitapVer.setText("Kitap Ver");
        kitapVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitapVerActionPerformed(evt);
            }
        });

        kitapAl.setText("Kitap Al");
        kitapAl.setMaximumSize(new java.awt.Dimension(67, 25));
        kitapAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitapAlActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setText("Geri");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Üye Adı", "Cinsiyet", "Doğum Tarihi", "Telefon", "E-mail", "Kitapları (id)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Kitap Adı", "Yazar Adı", "Yayın Evi", "Kitap Türü", "Kitap Durumu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(229, 229, 229)
                                .addComponent(kitapVer)
                                .addGap(151, 151, 151)
                                .addComponent(kitapAl, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 184, Short.MAX_VALUE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Feedback3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kitapAl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kitapVer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Feedback3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                    .addGap(30, 30, 30)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addGap(30, 30, 30)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void dinamikAra(String ara){
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        
        jTable1.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(ara));
    }
    
    public void dinamikAraUye(String ara){
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model2);
        
        jTable2.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(ara));
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jPanel1.setVisible(false);
        jPanel3.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jPanel1.setVisible(false);
        jPanel2.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void arama_cubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arama_cubuguKeyReleased
        String ara = arama_cubugu.getText();

        dinamikAra(ara);
    }//GEN-LAST:event_arama_cubuguKeyReleased

    private void Kitap_EkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kitap_EkleActionPerformed
        Feedback.setText("");

        String kitap_adi = Fld_kitap_adi.getText();
        String kitap_yazari = Fld_yazar_adi.getText();
        String yayin_evi = Fld_yayin_evi.getText();
        String kitap_turu = Box_Kitap_Turu.getSelectedItem().toString();
        String kitap_durumu = "Mevcut";

        veriIslemleri.kitapEkle(kitap_adi,kitap_yazari,yayin_evi,kitap_turu,kitap_durumu);
        kitapGoruntule();
        Feedback.setText("Yeni Kitap Başarılı Bir Şekilde Eklendi...");
    }//GEN-LAST:event_Kitap_EkleActionPerformed

    private void Box_Kitap_TuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_Kitap_TuruActionPerformed
        //SelectedValue = Box_Kitap_Turu.getSelectedItem().toString();
    }//GEN-LAST:event_Box_Kitap_TuruActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selectedRow = jTable1.getSelectedRow();

        Fld_kitap_adi.setText(model.getValueAt(selectedRow,1).toString());
        Fld_yazar_adi.setText(model.getValueAt(selectedRow,2).toString());
        Fld_yayin_evi.setText(model.getValueAt(selectedRow,3).toString());
        Box_Kitap_Turu.setSelectedItem(model.getValueAt(selectedRow,4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleActionPerformed
                
        String kitap_adi_G = Fld_kitap_adi.getText();
        String kitap_yazari_G = Fld_yazar_adi.getText();
        String yayin_evi_G = Fld_yayin_evi.getText();
        String kitap_turu_G = Box_Kitap_Turu.getSelectedItem().toString();

        int selectedrow = jTable1.getSelectedRow();
        if (selectedrow == -1) {
            if (model.getRowCount() == 0) {
                Feedback.setText("Kitaplar tablosu şu anda boş.");
            }
            else{
                Feedback.setText("Lütfen güncellemek için bir kitap seçiniz.");
            }
        }
        else{

            int id = (int)model.getValueAt(selectedrow,0);

            veriIslemleri.kitapGuncelle(id,kitap_adi_G,kitap_yazari_G,yayin_evi_G,kitap_turu_G);

            kitapGoruntule();

            Feedback.setText("Kitap başarılı bir şekilde güncellendi...");

        }
    }//GEN-LAST:event_guncelleActionPerformed

    private void silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silActionPerformed
        Feedback.setText("");

        int selectedrow = jTable1.getSelectedRow();

        if (selectedrow == -1) {
            if (model.getRowCount() == 0) {
                Feedback.setText("Kitaplar tablosu şu anda boş.");
            }
            else{
                Feedback.setText("Lütfen silinecek bir kitap seçiniz.");
            }
        }
        else{
            int id = (int)model.getValueAt(selectedrow,0);

            veriIslemleri.kitapSil(id);

            kitapGoruntule();

            Feedback.setText("Kitap başarılı bir şekilde silindi...");
        }

    }//GEN-LAST:event_silActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jPanel2.setVisible(false);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jPanel3.setVisible(false);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int selectedRow = jTable2.getSelectedRow();

        Fld_Uye_adi.setText(model2.getValueAt(selectedRow,1).toString());
        Box_Cinsiyet.setSelectedItem(model2.getValueAt(selectedRow,2).toString());
        Fld_dogum_tarihi.setText(model2.getValueAt(selectedRow,3).toString());
        Fld_Telefon.setText(model2.getValueAt(selectedRow,4).toString());
        Fld_Email.setText(model2.getValueAt(selectedRow,5).toString());
    }//GEN-LAST:event_jTable2MouseClicked

    private void sil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sil1ActionPerformed
        Feedback1.setText("");

        int selectedrow = jTable2.getSelectedRow();

        if (selectedrow == -1) {
            if (model2.getRowCount() == 0) {
                Feedback1.setText("Uyeler tablosu şu anda boş.");
            }
            else{
                Feedback1.setText("Lütfen silinecek bir uye seçiniz.");
            }
        }
        else{
            int id = (int)model2.getValueAt(selectedrow,0);

            veriIslemleri.uyeSil(id);

            uyeGoruntule();

            Feedback1.setText("Uye başarılı bir şekilde silindi...");
        }
    }//GEN-LAST:event_sil1ActionPerformed

    private void guncelle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelle1ActionPerformed

        String uye_adi_G = Fld_Uye_adi.getText();
        String telefon_G = Fld_Telefon.getText();
        String dogum_tarihi_G = Fld_dogum_tarihi.getText();
        String e_mail_G = Fld_Email.getText();
        String cinsiyet_G = Box_Cinsiyet.getSelectedItem().toString();

        int selectedrow = jTable2.getSelectedRow();
        if (selectedrow == -1) {
            if (model2.getRowCount() == 0) {
                Feedback1.setText("Üyeler tablosu şu anda boş.");
            }
            else{
                Feedback1.setText("Lütfen güncellemek için bir üye seçiniz.");
            }
        }
        else{

            int id = (int)model2.getValueAt(selectedrow,0);

            veriIslemleri.uyeGuncelle(id,uye_adi_G,cinsiyet_G,dogum_tarihi_G,telefon_G,e_mail_G);

            uyeGoruntule();

            Feedback1.setText("Üye başarılı bir şekilde güncellendi...");

        }
    }//GEN-LAST:event_guncelle1ActionPerformed

    private void Box_CinsiyetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_CinsiyetActionPerformed
        //SelectedValue = Box_Kitap_Turu.getSelectedItem().toString();
    }//GEN-LAST:event_Box_CinsiyetActionPerformed

    private void Uye_EkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Uye_EkleActionPerformed
        Feedback1.setText("");

        String uye_adi = Fld_Uye_adi.getText();
        String telefon = Fld_Telefon.getText();
        String dogum_tarihi = Fld_dogum_tarihi.getText();
        String e_mail = Fld_Email.getText();
        String cinsiyet = Box_Cinsiyet.getSelectedItem().toString();

        veriIslemleri.uyeEkle(uye_adi,cinsiyet,dogum_tarihi,telefon,e_mail);
        uyeGoruntule();
        Feedback1.setText("Yeni Kitap Başarılı Bir Şekilde Eklendi...");
    }//GEN-LAST:event_Uye_EkleActionPerformed

    private void Fld_dogum_tarihiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fld_dogum_tarihiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Fld_dogum_tarihiActionPerformed

    private void arama_cubugu1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arama_cubugu1KeyReleased
        String ara = arama_cubugu1.getText();

        dinamikAraUye(ara);
    }//GEN-LAST:event_arama_cubugu1KeyReleased

    private void kitapVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitapVerActionPerformed

        int kitaplari = kitapid;
        int selectedrow = jTable4.getSelectedRow();
        
        if (selectedrow == -1) {
            if (model4.getRowCount() == 0) {
                Feedback3.setText("Kitaplar tablosu şu anda boş.");
            }
            else{
                Feedback3.setText("Lütfen ödünç vermek için bir kitap seçiniz.");
            }
        }
        else{
            
            if(kitap_durumu_GE.equals("Mevcut")){
            veriIslemleri.kitapVer(kitapid,kitap_adi_GE,kitap_yazari_GE,yayin_evi_GE,kitap_turu_GE,kitap_durumu_GE);
            }
            else{
            Feedback3.setText("Kitap Mevcut Değil!");
            }
            
            kitapGoruntuleOdunc();

            Feedback3.setText("Kitap başarılı bir şekilde ödünç verildi.");

        }
        
        if (selectedrow == -1) {
            if (model3.getRowCount() == 0) {
                Feedback3.setText("Üyeler tablosu şu anda boş.");
            }
            else{
                Feedback3.setText("Lütfen ödünç vermek için bir üye seçiniz.");
            }
        }
        else{
            
            if(kitap_durumu_GE.equals("Mevcut")){
            veriIslemleri.uyeyeVer(uyeid,uye_adi_GE,cinsiyet_GE,dogum_tarihi_GE,telefon_GE,e_mail_GE, kitaplari);
            Feedback3.setText("Kitap başarılı bir şekilde ödünç verildi.");
            }
            else{
                Feedback3.setText("Kitap Mevcut Değil!");
            }
            
            uyeGoruntuleOdunc();
        }
    }//GEN-LAST:event_kitapVerActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        int selectedRow = jTable3.getSelectedRow();
        
        uyeid = (int) jTable3.getValueAt(selectedRow, 0);
        uye_adi_GE = jTable3.getValueAt(selectedRow, 1).toString();
        cinsiyet_GE = jTable3.getValueAt(selectedRow, 2).toString();
        dogum_tarihi_GE = jTable3.getValueAt(selectedRow, 3).toString();
        telefon_GE = jTable3.getValueAt(selectedRow, 4).toString();
        e_mail_GE = jTable3.getValueAt(selectedRow, 5).toString();
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jPanel4.setVisible(false);
        jPanel2.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void kitapAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitapAlActionPerformed
        int selectedrow = jTable4.getSelectedRow();
        int kitaplari = 0;
        
        if (selectedrow == -1) {
            if (model4.getRowCount() == 0) {
                Feedback3.setText("Kitaplar tablosu şu anda boş.");
            }
            else{
                Feedback3.setText("Lütfen ödünç vermek için bir kitap seçiniz.");
            }
        }
        else{
            if(kitap_durumu_GE.equals("Mevcut Değil")){
                veriIslemleri.kitapAl(kitapid,kitap_adi_GE,kitap_yazari_GE,yayin_evi_GE,kitap_turu_GE,kitap_durumu_GE);
            }
            else{
                Feedback3.setText("Kitap Mevcut!");  
            }
            
            kitapGoruntuleOdunc();

            Feedback3.setText("Kitap başarılı bir şekilde ödünç verildi.");

        }
        
        if (selectedrow == -1) {
            if (model3.getRowCount() == 0) {
                Feedback3.setText("Üyeler tablosu şu anda boş.");
            }
            else{
                Feedback3.setText("Lütfen ödünç vermek için bir üye seçiniz.");
            }
        }
        else{
            
            if(kitap_durumu_GE.equals("Mevcut Değil")){
            veriIslemleri.uyeyeVer(uyeid,uye_adi_GE,cinsiyet_GE,dogum_tarihi_GE,telefon_GE,e_mail_GE, kitaplari);
            Feedback3.setText("Kitap başarılı bir şekilde ödünç verildi.");
            }
            else{
                Feedback3.setText("Kitap Mevcut!");
            }
            
            uyeGoruntuleOdunc();
        }
    }//GEN-LAST:event_kitapAlActionPerformed

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        int selectedRow = jTable4.getSelectedRow();

        kitapid = (int) jTable4.getValueAt(selectedRow, 0);
        kitap_adi_GE = jTable4.getValueAt(selectedRow, 1).toString();
        kitap_yazari_GE = jTable4.getValueAt(selectedRow, 2).toString();
        yayin_evi_GE = jTable4.getValueAt(selectedRow, 3).toString();
        kitap_turu_GE = jTable4.getValueAt(selectedRow, 4).toString();
        kitap_durumu_GE = jTable4.getValueAt(selectedRow, 5).toString();
    }//GEN-LAST:event_jTable4MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jPanel2.setVisible(false);
        jPanel4.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    public void kitapGoruntule(){
        model.setRowCount(0);

        ArrayList<Kitaplar> kitaplar = new ArrayList<Kitaplar>();
        
        kitaplar = veriIslemleri.kitaplariGetir();
        
        if (kitaplar != null) {
            for(Kitaplar Kitaplar : kitaplar){
                Object[] eklenecek = {Kitaplar.getId(),Kitaplar.getKitap_adi(),Kitaplar.getKitap_yazari(),Kitaplar.getYayin_evi(),Kitaplar.getKitap_turu(), Kitaplar.getKitap_durumu()};
                
                model.addRow(eklenecek);
            }
        }
    }
        public void kitapGoruntuleOdunc(){
        model4.setRowCount(0);

        ArrayList<Kitaplar> kitaplar = new ArrayList<Kitaplar>();
        
        kitaplar = veriIslemleri.kitaplariGetir();
        
        if (kitaplar != null) {
            for(Kitaplar Kitaplar : kitaplar){
                Object[] eklenecek = {Kitaplar.getId(),Kitaplar.getKitap_adi(),Kitaplar.getKitap_yazari(),Kitaplar.getYayin_evi(),Kitaplar.getKitap_turu(), Kitaplar.getKitap_durumu()};

                model4.addRow(eklenecek);
            }
        }
    }
    
    public void uyeGoruntule(){
        model2.setRowCount(0);
          
        ArrayList<Uyeler> uyeler = new ArrayList<Uyeler>();
        
        uyeler = veriIslemleri.uyeleriGetir();
        
        if (uyeler != null) {
            for(Uyeler Uyeler : uyeler){
                Object[] eklenecek1 = {Uyeler.getId(), Uyeler.getKullanici_adi(), Uyeler.getCinsiyet(), Uyeler.getDogum_tarihi(), Uyeler.getTelefon(), Uyeler.getE_mail(), Uyeler.getKitaplari()};
                
                model2.addRow(eklenecek1);
            }
        }
    }
    
    public void uyeGoruntuleOdunc(){
        model3.setRowCount(0);
          
        ArrayList<Uyeler> uyeler = new ArrayList<Uyeler>();
        
        uyeler = veriIslemleri.uyeleriGetir();
        
        if (uyeler != null) {
            for(Uyeler Uyeler : uyeler){
                Object[] eklenecek1 = {Uyeler.getId(), Uyeler.getKullanici_adi(), Uyeler.getCinsiyet(), Uyeler.getDogum_tarihi(), Uyeler.getTelefon(), Uyeler.getE_mail(), Uyeler.getKitaplari()};
                
                model3.addRow(eklenecek1);
            }
        }
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Box_Cinsiyet;
    private javax.swing.JComboBox<String> Box_Kitap_Turu;
    private javax.swing.JLabel Feedback;
    private javax.swing.JLabel Feedback1;
    private javax.swing.JLabel Feedback3;
    private javax.swing.JTextField Fld_Email;
    private javax.swing.JTextField Fld_Telefon;
    private javax.swing.JTextField Fld_Uye_adi;
    private javax.swing.JTextField Fld_dogum_tarihi;
    private javax.swing.JTextField Fld_kitap_adi;
    private javax.swing.JTextField Fld_yayin_evi;
    private javax.swing.JTextField Fld_yazar_adi;
    private javax.swing.JButton Kitap_Ekle;
    private javax.swing.JButton Uye_Ekle;
    private javax.swing.JTextField arama_cubugu;
    private javax.swing.JTextField arama_cubugu1;
    private javax.swing.JButton guncelle;
    private javax.swing.JButton guncelle1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JButton kitapAl;
    private javax.swing.JButton kitapVer;
    private javax.swing.JButton sil;
    private javax.swing.JButton sil1;
    // End of variables declaration//GEN-END:variables
}
